/*
 * Bank API Mock
 *
 * Mock of a Bank API  
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kmahmassani@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using BankAPI.Attributes;

using Microsoft.AspNetCore.Authorization;
using BankAPI.Models;

namespace BankAPI.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class PaymentsApiController : ControllerBase
    { 
        /// <summary>
        /// Process a card payment
        /// </summary>
        /// <remarks>Processes a payment and returns success or failure </remarks>
        /// <param name="body"></param>
        /// <response code="201">Payment processed successfully</response>
        /// <response code="401">Unauthorized</response>
        /// <response code="422">Invalid data was sent</response>
        /// <response code="502">Bad gateway</response>
        [HttpPost]
        [Route("/process-card")]
        [ValidateModelState]
        [SwaggerOperation("ProcessCardPost")]
        [SwaggerResponse(statusCode: 201, type: typeof(PaymentResponse), description: "Payment processed successfully")]
        public virtual IActionResult ProcessCardPost([FromBody]PaymentRequest body)
        { 
            // Approval or rejection will be based on the first digit of the card number
            var retval = new PaymentResponse()
            {
                Id = Guid.NewGuid().ToString(),
                Approved = int.Parse(body.Number.Substring(0,1)) % 2 == 0,
                AuthCode = body.Number.Substring(3,4)
            };

            return new ObjectResult(retval);
        }
    }
}
