#!/usr/bin/env bash
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
#

dotnet restore src/BankAPI/ && \
    dotnet build src/BankAPI/ && \
    echo "Now, run the following to start the project: dotnet run -p src/BankAPI/BankAPI.csproj --launch-profile web"
