/*
 * Bank API Mock
 *
 * Mock of a Bank API  
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kmahmassani@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace BankAPI.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class PaymentResponse
    { 
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [Required]
        [DataMember(Name="id")]
        public string Id { get; set; }

        /// <summary>
        /// Whether or not the authorization or capture was successful
        /// </summary>
        /// <value>true</value>
        [Required]
        [DataMember(Name="approved")]
        public bool? Approved { get; set; }        

        /// <summary>
        /// AuthCode
        /// </summary>
        /// <value>0200</value>
        [Required]
        [DataMember(Name="authcode")]
        public string AuthCode { get; set; } 

    }
}
